/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    okep_1: THREE.Mesh;
    okep_2: THREE.Mesh;
    okep_3: THREE.Mesh;
    okep_4: THREE.Mesh;
  };
  materials: {
    ["Wax_02.003"]: THREE.MeshPhysicalMaterial;
    Color_D02: THREE.MeshPhysicalMaterial;
    MICRO_WORLD__3_: THREE.MeshPhysicalMaterial;
    fi: THREE.MeshPhysicalMaterial;
  };
};

export function MicrowModel(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/models/hall.glb") as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.okep_1.geometry}
          material={materials["Wax_02.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.okep_2.geometry}
          material={materials.Color_D02}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.okep_3.geometry}
          material={materials.MICRO_WORLD__3_}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.okep_4.geometry}
          material={materials.fi}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/hall.glb");